/*
 * ESP32 Message ID Fix
 * 
 * The ESP32 Xtensa compiler doesn't properly zero-extend message ID constants
 * when passing them as uint32_t parameters. This causes corruption.
 * 
 * This fix redefines all message ID constants to explicitly cast to uint32_t
 */

#pragma once

#if CONFIG_HAL_BOARD == HAL_BOARD_ESP32

// Save original values
#define MAVLINK_MSG_ID_HEARTBEAT_ORIG MAVLINK_MSG_ID_HEARTBEAT
#define MAVLINK_MSG_ID_SYS_STATUS_ORIG MAVLINK_MSG_ID_SYS_STATUS
#define MAVLINK_MSG_ID_PARAM_VALUE_ORIG MAVLINK_MSG_ID_PARAM_VALUE
#define MAVLINK_MSG_ID_PARAM_SET_ORIG MAVLINK_MSG_ID_PARAM_SET
#define MAVLINK_MSG_ID_GPS_RAW_INT_ORIG MAVLINK_MSG_ID_GPS_RAW_INT
#define MAVLINK_MSG_ID_RAW_IMU_ORIG MAVLINK_MSG_ID_RAW_IMU
#define MAVLINK_MSG_ID_ATTITUDE_ORIG MAVLINK_MSG_ID_ATTITUDE
#define MAVLINK_MSG_ID_ATTITUDE_QUATERNION_ORIG MAVLINK_MSG_ID_ATTITUDE_QUATERNION
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT_ORIG MAVLINK_MSG_ID_GLOBAL_POSITION_INT

// Redefine with explicit cast
#undef MAVLINK_MSG_ID_HEARTBEAT
#undef MAVLINK_MSG_ID_SYS_STATUS  
#undef MAVLINK_MSG_ID_PARAM_VALUE
#undef MAVLINK_MSG_ID_PARAM_SET
#undef MAVLINK_MSG_ID_GPS_RAW_INT
#undef MAVLINK_MSG_ID_RAW_IMU
#undef MAVLINK_MSG_ID_ATTITUDE
#undef MAVLINK_MSG_ID_ATTITUDE_QUATERNION
#undef MAVLINK_MSG_ID_GLOBAL_POSITION_INT

#define MAVLINK_MSG_ID_HEARTBEAT ((uint32_t)0)
#define MAVLINK_MSG_ID_SYS_STATUS ((uint32_t)1)
#define MAVLINK_MSG_ID_PARAM_VALUE ((uint32_t)22)
#define MAVLINK_MSG_ID_PARAM_SET ((uint32_t)23)
#define MAVLINK_MSG_ID_GPS_RAW_INT ((uint32_t)24)
#define MAVLINK_MSG_ID_RAW_IMU ((uint32_t)27)
#define MAVLINK_MSG_ID_ATTITUDE ((uint32_t)30)
#define MAVLINK_MSG_ID_ATTITUDE_QUATERNION ((uint32_t)31)
#define MAVLINK_MSG_ID_GLOBAL_POSITION_INT ((uint32_t)33)

// Add more as needed...

#endif // CONFIG_HAL_BOARD == HAL_BOARD_ESP32